[tool.ruff]
extend = "../pyproject.toml"
extend-ignore = [
    "D100",  # Missing doc string in public module.
    "D101",  # Missing doc string in public class.
    "D102",  # Missing doc string in public method.
    "D103",  # Missing doc string in public function.
    "D104",  # Missing doc string in public package.
]
